inventory/locations/forms.py
from wtforms_alchemy import ModelForm
from flask_wtf import Form
from inventory.models import Location


class LocationForm(ModelForm, Form):
    class Meta:
        model = Location
        include = ['name', 'address']

inventory/movements/forms.py
from wtforms_alchemy.fields import QuerySelectField
from wtforms_alchemy import ModelForm
from flask_wtf import Form
from inventory.models import Product, Location, Movement


class MovementForm(ModelForm, Form):
    class Meta:
        model = Movement
    from_location = QuerySelectField(
        query_factory=lambda: Location.query.all(),
        get_pk=lambda a: a.location_id,
        get_label=lambda a: a.name,
        allow_blank=True,
    )
    to_location = QuerySelectField(
        query_factory=lambda: Location.query.all(),
        get_pk=lambda a: a.location_id,
        get_label=lambda a: a.name,
        allow_blank=True,
    )
    product = QuerySelectField(
        query_factory=lambda: Product.query.all(),
        get_pk=lambda a: a.product_id,
        get_label=lambda a: "{0} ({1})".format(a.name, str(a.warehouse)),
        allow_blank=False,
    )

    def validate_product(self, field):
        if self.from_location.data and field.data:
            if not field.data.warehouse:
                self.product.errors.append('The product does not belong to any warehouse yet.')

    def validate_from_location(self, field):
        result = True

        if not field.data and not self.to_location.data:
            self.from_location.errors.append('Enter at least one of the locations.')
            result = False

        if field.data:
            if self.product.data.warehouse != field.data:
                self.from_location.errors.append('The product does not belong to this location.')
            elif field.data.get_product_quantity(self.product.data.name)<self.qty.data:
                self.from_location.errors.append('Location does not have enough stock. Available quantity: {0}'.format(field.data.get_product_quantity(self.product.data.name)))
            result = False

        if field.data and self.to_location.data:
            if self.from_location.data == self.to_location.data:
                self.from_location.errors.append('From Location can\'t be same as To Location.')
                result = False

        return result

    def validate_qty(self, field):
        result = True
        if not self.from_location.data and self.to_location.data:
            products = Product.query.all()
            products = [product for product in products if self.product.data.name==product.name and not product.warehouse]
            if not products:
                self.qty.errors.append('No products available! Please create some and then try adding or try moving From some Location.')
                return False
            
            elif len(products) < field.data:
                self.qty.errors.append('Only {0} item(s) available! Please create more of them.'.format(len(products)))
                return False
        return result

inventory/products/forms.py
from wtforms_alchemy import ModelForm
from flask_wtf import Form
from inventory.models import Product


class ProductForm(ModelForm, Form):
    class Meta:
        model = Product
        include = ['name']

inventory/locations/routes.py
from flask import Blueprint
from flask import render_template, url_for, flash, redirect, request, abort
from flask_login import current_user, login_required
from inventory import db
from inventory.models import Location
from .forms import LocationForm

locations = Blueprint('locations', __name__)

@locations.route("/locations")
def list_locations():
    page = request.args.get('page', 1, type=int)
    locations = Location.query.paginate(page=page, per_page=10)
    return render_template('locations.html', locations=locations, title='Locations')


@locations.route("/location/<int:location_id>")
def location(location_id):
    location = Location.query.get_or_404(location_id)
    return render_template('location.html', title=location.name, location=location, legend='Location Details')

@locations.route("/location/new", methods=['GET', 'POST'])
@login_required
def new_location():
    form = LocationForm()
    if form.validate_on_submit():
        location = Location(name=form.name.data, address=form.address.data, creator=current_user)
        db.session.add(location)
        db.session.commit()
        flash_message = 'The Location has been added!'
        flash(flash_message, 'success')
        return redirect(url_for('locations.list_locations'))
    return render_template('create_location.html', title="New Location", form=form, legend='Add a new Location')

@locations.route("/location/<int:location_id>/update", methods=['GET', 'POST'])
@login_required
def update_location(location_id):
    location = Location.query.get_or_404(location_id)
    if location.creator != current_user:
        abort(403)
    form = LocationForm()
    if form.validate_on_submit():
        location.name = form.name.data
        location.address = form.address.data
        db.session.commit()
        flash('The location has been updated!', 'success')
        return redirect(url_for('locations.location', location_id=location.location_id))
    elif request.method == 'GET':
        form.name.data = location.name
        form.address.data = location.address
    return render_template('create_location.html', title="Update Location", form=form, legend='Update Location')

@locations.route("/location/<int:location_id>/delete", methods=['POST'])
@login_required
def delete_location(location_id):
    location = Location.query.get_or_404(location_id)
    if location.creator != current_user:
        abort(403)
    db.session.delete(location)
    db.session.commit()
    flash('The location has been deleted', 'success')
    return redirect(url_for('locations.list_locations'))

inventory/movements/routes.py
from flask import Blueprint
from flask import render_template, url_for, flash, redirect, request, abort
from flask_login import current_user, login_required
from inventory.models import Movement, Product
from inventory import db
from .forms import MovementForm

movements = Blueprint('movements', __name__)


@movements.route("/movements")
def list_movements():
    page = request.args.get('page', 1, type=int)
    movements = Movement.query.order_by(Movement.timestamp.desc()).paginate(page=page, per_page=10)
    return render_template('movements.html', movements=movements, title='Movements')

@movements.route("/movement/<int:movement_id>")
def movement(movement_id):
    movement = Movement.query.get_or_404(movement_id)
    return render_template('movement.html', title=movement, movement=movement, legend='Movement Details')

@movements.route("/movement/new", methods=['GET', 'POST'])
@login_required
def new_movement():
    form = MovementForm()
    if form.validate_on_submit():
        from_location = form.from_location.data if hasattr(form, 'from_location') else None
        to_location = form.to_location.data if hasattr(form, 'to_location') else None
        product = form.product.data
        qty = form.qty.data

        if from_location and to_location:
            products = db.session.query(Product).filter(Product.warehouse==from_location).all()
            products_transferred = 0
            for item in products:
                if item.name == product.name and products_transferred<qty:
                    products_transferred+=1
                    item.warehouse = to_location
                    db.session.add(item)
            db.session.commit()
            flash_msg = 'The products have been successfully shifted'

        elif from_location or to_location:
            if from_location and from_location.get_product_quantity(product.name)>= qty:
                products = db.session.query(Product).filter(Product.warehouse==from_location).all()
                for product in products:
                    product.warehouse = None
                db.session.commit()
                flash_msg = 'The products have been successfully removed!'
            elif to_location:
                products_to_add = []
                products = db.session.query(Product).filter(Product.name==product.name)
                products_transferred = 0
                for product in products:
                    if not product.warehouse and products_transferred<qty:
                        products_transferred+=1
                        product.warehouse = to_location
                        products_to_add.append(product)
                db.session.add_all(products_to_add)
                db.session.commit()
                flash_msg = '{0} {1}(s) have been added in the warehouse {2}!'.format(len(products_to_add), product.name, to_location)
        product_id = product.product_id
        movement = Movement(product_id=product_id, qty=qty, 
                        from_location=from_location,
                        to_location=to_location, creator=current_user)
        db.session.add(movement)
        db.session.commit()
        flash(flash_msg, 'success')
        return redirect(url_for('movements.list_movements'))
    return render_template('create_movement.html', title="New Movement", form=form, legend='Add a new Movement')


@movements.route("/movement/<int:movement_id>/update", methods=['GET', 'POST'])
@login_required
def update_movement(movement_id):
    movement = Movement.query.get_or_404(movement_id)
    if movement.creator != current_user:
        abort(403)
    form = MovementForm()
    if form.validate_on_submit():
        movement.from_location = form.from_location.data
        movement.to_location = form.to_location.data
        movement.qty = form.qty.data
        movement.product = form.product.data
        db.session.commit()
        flash('The movement has been updated!', 'success')
        return redirect(url_for('movements.movement', movement_id=movement.movement_id))
    elif request.method == 'GET':
        form.from_location.data = movement.from_location
        form.to_location.data = movement.to_location
        form.product.data = movement.product
        form.qty.data = movement.qty
    return render_template('create_movement.html', title="Update Movement", form=form, legend='Update Movement')

@movements.route("/movement/<int:movement_id>/delete", methods=['POST'])
@login_required
def delete_movement(movement_id):
    movement = Movement.query.get_or_404(movement_id)
    if movement.creator != current_user:
        abort(403)
    db.session.delete(movement)
    db.session.commit()
    flash('The movement has been deleted', 'success')
    return redirect(url_for('movements.list_movements'))

inventory/products/routes.py
from flask import Blueprint
from flask import render_template, url_for, flash, redirect, request, abort
from flask_login import current_user, login_required
from inventory import db
from inventory.models import Product
from .forms import ProductForm


products = Blueprint('products', __name__)


@products.route("/")
def show_report():
    page = request.args.get('page', 1, type=int)
    products = Product.query.paginate(page=page, per_page=10)
    return render_template('report.html', products=products, title='Report')

@products.route("/products")
def list_products():
    page = request.args.get('page', 1, type=int)
    products = Product.query.paginate(page=page, per_page=10)
    return render_template('products.html', products=products, title='Products')

@products.route("/product/<int:product_id>")
def product(product_id):
    product = Product.query.get_or_404(product_id)
    return render_template('product.html', title=product.name, product=product, legend='Product Details')

@products.route("/product/new", methods=['GET', 'POST'])
@login_required
def new_product():
    form = ProductForm()
    if form.validate_on_submit():
        product = Product(name=form.name.data)
        product.creator=current_user
        db.session.add(product)
        db.session.commit()
        flash_message = 'The product has been added!'
        flash(flash_message, 'success')
        return redirect(url_for('products.list_products'))
    return render_template('create_product.html', title="New Product", form=form, legend='New Product')

@products.route("/product/<int:product_id>/update", methods=['GET', 'POST'])
@login_required
def update_product(product_id):
    product = Product.query.get_or_404(product_id)
    if product.creator != current_user:
        abort(403)
    form = ProductForm()
    if form.validate_on_submit():
        product.name = form.name.data
        db.session.commit()
        flash('The product has been updated!', 'success')
        return redirect(url_for('products.product', product_id=product.product_id))
    elif request.method == 'GET':
        form.name.data = product.name
    return render_template('create_product.html', title="Update Product", form=form, legend='Update Product')

@products.route("/product/<int:product_id>/delete", methods=['POST'])
@login_required
def delete_product(product_id):
    product = Product.query.get_or_404(product_id)
    if product.creator != current_user:
        abort(403)
    db.session.delete(product)
    db.session.commit()
    flash('The product has been deleted', 'success')
    return redirect(url_for('products.list_products'))

inventory/users/routes.py
from flask import Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask import render_template, url_for, flash, redirect, request, abort
from inventory import db, bcrypt
from .forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from inventory.models import User
from .utils import save_picture, send_reset_email


users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('products.show_report'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash_message = 'Your account has been created!'
        flash(flash_message, 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title="Register", form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('products.show_report'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('products.show_report'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', title="Login", form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('products.show_report'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title="Account", image_file=image_file, form=form)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('products.show_report'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('products.show_report'))
    user = User.verify_reset_token(token)
    if not user:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash_message = 'Your password has been updated!'
        flash(flash_message, 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)    

inventory/templates/layout.html
<!DOCTYPE html>
<html>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css"
    integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

  {% if title %}
  <title>Flask Blog - {{ title }}</title>
  {% else %}
  <title>DJ's Inventory</title>
  {% endif %}
</head>

<body>
  <header class="site-header">
    <nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand mr-4" href="/">DJ's Inventory</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{{ url_for('products.list_products') }}">Products</a>
            <a class="nav-item nav-link" href="{{ url_for('locations.list_locations') }}">Locations</a>
            <a class="nav-item nav-link" href="{{ url_for('movements.list_movements') }}">Product Movements</a>
            <a class="nav-item nav-link" href="{{ url_for('products.show_report') }}">Report</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
            <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container" style="padding-top: 70px;">
    <div class="row">
      <div class="col-md-8">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock content %}
      </div>
    </div>
  </main>


  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  {% block scripts %}{% endblock scripts %}

</body>

</html>

inventory/templates/location.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section">

    <div class="media-body">
        <div class="article-metadata">
            {% if location.creator == current_user %}
            <p>Added by: <a class="mr-2" href="{{ url_for('users.account') }}">You</a></p>
            <span class="pull-right">
                <a href="{{ url_for('locations.update_location', location_id=location.location_id) }}"
                    data-balloon="edit this location" class="text-info">
                    <i class="fas fa-edit"></i>
                </a>
                <a href="#" data-balloon="remove this location" class="text-danger" data-toggle="modal"
                    data-target="#deleteModal">
                    <i class="fas fa-trash"></i>
                </a>
            </span>
            {% else %}
            <p>Added by: {{ location.creator }}</p>
            {% endif %}
        </div>
        <h3 class="article-title">{{ legend }}</h3>
        <p class="article-content"><strong>Id: </strong>{{ location.location_id }}</p>
        <p class="article-content"><strong>Name: </strong>{{ location.name }}</p>
        <Address class="article-content"><strong>Address:</strong> {{ location.address }}</Address>
        <p class="article-content"><strong>Total Products: </strong>{{ location.get_total_stock }}</p>
    </div>
</article>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Location?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('locations.delete_location', location_id=location.location_id) }}"
                    method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

inventory/templates/movement.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section">

    <div class="media-body">
        <div class="article-metadata">
            {% if movement.creator == current_user %}
            <p>Added by: <a class="mr-2" href="{{ url_for('users.account') }}">You</a></p>
            <span class="pull-right">
                <a href="{{ url_for('movements.update_movement', movement_id=movement.movement_id) }}"
                    data-balloon="edit this movement" class="text-info">
                    <i class="fas fa-edit"></i>
                </a>
                <a href="#" data-balloon="remove this movement" class="text-danger" data-toggle="modal"
                    data-target="#deleteModal">
                    <i class="fas fa-trash"></i>
                </a>
            </span>
            {% else %}
            <p>Added by: {{ movement.creator }}</p>
            {% endif %}
        </div>
        <h3 class="article-title">{{ legend }}</h3>

        <p class="article-content"><strong>Movement Id: </strong>{{ movement.movement_id }}</p>
        <p class="article-content"><strong>Date: </strong>{{ movement.timestamp.strftime('%d-%m-%Y %H:%M:%S') }}</p>
        <p class="article-content"><strong>From Location: </strong>{{ movement.from_location }}</p>
        <p class="article-content"><strong>To Location: </strong>{{ movement.to_location }}</p>
        <p class="article-content"><strong>Product: </strong>{{ movement.product }}</p>
        <p class="article-content"><strong>Quantity: </strong>{{ movement.qty }}</p>
    </div>
</article>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Movement?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('movements.delete_movement', movement_id=movement.movement_id) }}"
                    method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

inventory/templates/product.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            {% if product.creator == current_user %}
            <p>Added by: <a class="mr-2" href="{{ url_for('users.account') }}">You</a></p>
            <span class="pull-right">
                <a href="{{ url_for('products.update_product', product_id=product.product_id) }}"
                    data-balloon="edit this product" class="text-info">
                    <i class="fas fa-edit"></i>
                </a>
                <a href="#" data-balloon="remove this product" class="text-danger" data-toggle="modal"
                    data-target="#deleteModal">
                    <i class="fas fa-trash"></i>
                </a>
            </span>
            {% else %}
            <p>Added by: {{ product.creator }}</p>
            {% endif %}
        </div>
        <h3 class="article-title">{{ legend }}</h3>

        <p class="article-content"><strong>Id:</strong>{{ product.product_id }}</p>
        <p class="article-content"><strong>Name:</strong>{{ product.name }}</p>
        <p class="article-content"><strong>Warehouse:</strong>{{ product.warehouse }}</p>
    </div>
</article>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Product?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('products.delete_product', product_id=product.product_id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

inventory/templates/products.html
{% extends "layout.html" %}
{% block content %}

<section>
  <div class="row">
    <a href="{{ url_for('products.new_product') }}" class="btn btn-primary btn-md active mb-4" role="button"
      aria-pressed="true">Add New Product</a><br>
    <table class="table table-hover table-bordered text-center">
      <tr class="text-center">
        <th>Id.</th>
        <th>Product</th>
        <th>Location</th>
      </tr>
      {% for product in products.items %}
      <tr>
        <td>{{ product.product_id }}</td>
        <td>
          <a href="{{ url_for('products.product', product_id = product.product_id)}}">{{ product.name }}</a>
        </td>
        <td>
          {{ product.warehouse }}
        </td>
      </tr>


      <!-- Modal -->
      <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModalLabel">Delete Product?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <form action="{{ url_for('products.delete_product', product_id=product.product_id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
              </form>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}

    </table>

  </div>
</section>
{% for page_num in products.iter_pages(left_edge = 1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
{% if products.page == page_num %}
<a class="btn btn-info mb-4" href="{{ url_for('products.list_products', page=page_num )}}">{{ page_num }}</a>
{% else %}
<a class="btn btn-outline-info mb-4" href="{{ url_for('products.list_products', page=page_num )}}">{{ page_num }}</a>
{% endif %}
{% else %}
...
{% endif %}
{% endfor %}
{% endblock content %}

{% block scripts %}
<script>
  function confirm_delete() {
    return confirm("Do you want to remove this product?");
  }
</script>
{% endblock scripts %}